### PR TITLE
TES backend bugfix

### PR DESCRIPTION
**Pull request by adamstruck**
I messed up a few things in the last few commits of my previous PR.

### CODE REVIEW

**Comment by adamstruck** [comment]
I also seem to be having issues with `InitialWorkDirRequirement`.  The input file doesn't seem to be mapped into the working directory.  Not sure what has changed since  I opened #409 but now instead of the input being passed to Funnel twice it is passed once, but is mounted incorrectly.

So I am not sure if this is something I messed up or due to another change.

**Comment by milos-ljubinkovic** [comment]
Yeah, you removed one of the 2 getRequirements(bindings) calls. InitialWorkDirRequirement is only properly created/populated after the bindings.preprocess method is called so you need to put the second one back.

**Comment by adamstruck** [comment]
That didn't seem to do the trick. This InitialWorkDirRequirement issue appears to be present prior to my previous PR.

**Comment by adamstruck** [comment]
I was able to fix this issue in https://github.com/rabix/bunny/pull/426/commits/9da61f58e4bf957dc972323ba92a593f092adf55. Can you confirm that this fix looks correct?

**Comment by milos-ljubinkovic** [comment]
Looks ok just add a null check for the resources, some tests are failing. Also test to see if [this](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/initialworkdirrequirement-docker-out.cwl) wf properly stages the secondary file on s3

**Comment by adamstruck** [comment]
The workflow you referenced does work and stages the secondary file output on s3.  

The TES backend currently uploads all files in its working directory.  I think we may want to be more specific about defining outputs in the TES message in the future, but the current approach seems to be working for now.

**Pull request merged**
